# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Application Programming Interfaces and Relational Databases 
author: Scott J. Brandenberg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Add a bibtex file so that we can create citations


launch_buttons:
  notebook_interface: "jupyterlab"
  
# Information about where the book exists on the web
repository:
  url: https://github.com/DesignSafe-Training/database-api  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
